"""add offers columns on product and category table

Revision ID: 8e7cc8eaceae
Revises: dd3bed9a4caa
Create Date: 2023-10-03 00:00:44.477904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7cc8eaceae'
down_revision: Union[str, None] = 'dd3bed9a4caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('in_offer', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('in_offer', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'discount')
    op.drop_column('product', 'in_offer')
    op.drop_column('category', 'discount')
    op.drop_column('category', 'in_offer')
    # ### end Alembic commands ###
